# Generated by Django 2.1 on 2018-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='product_guid',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventories',
            name='stores_guid',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_guid',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product_guid',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='guid',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='guid',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
