# Generated by Django 2.1 on 2018-08-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0002_auto_20180825_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sort',
            field=models.IntegerField(null=True),
        ),
    ]
