# Generated by Django 2.1 on 2018-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0003_auto_20180827_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='parent_giud',
            new_name='parent_guid',
        ),
        migrations.AlterField(
            model_name='section',
            name='sort',
            field=models.IntegerField(),
        ),
    ]
