# Generated by Django 2.1 on 2018-08-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0008_auto_20180828_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='currency_guid',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='price_guid',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='product_guid',
        ),
        migrations.AddField(
            model_name='prices',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Currency'),
        ),
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Price'),
        ),
        migrations.AddField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Product'),
        ),
    ]
