# Generated by Django 2.1 on 2018-08-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0010_auto_20180828_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterField(
            model_name='inventories',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_inventories', to='san_site.Product'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_prices', to='san_site.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
