# Generated by Django 2.1 on 2018-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0011_auto_20180830_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parent_guid',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
