# Generated by Django 2.1.1 on 2018-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0013_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='change_password',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
