# Generated by Django 2.1.1 on 2018-09-02 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0014_customer_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='inventories',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='price',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='prices',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='sort',
            field=models.IntegerField(default=500),
        ),
    ]
