# Generated by Django 2.1.1 on 2018-09-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0018_auto_20180903_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Currency')),
            ],
        ),
    ]
