# Generated by Django 2.1.1 on 2018-09-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0019_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='urfr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='urfr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='prices',
            name='urfr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urfr',
            field=models.FloatField(default=0),
        ),
    ]
