# Generated by Django 2.1.1 on 2018-09-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0020_auto_20180903_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventories',
            name='urfr',
        ),
        migrations.RemoveField(
            model_name='person',
            name='urfr',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='urfr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urfr',
        ),
    ]
