# Generated by Django 2.1.1 on 2018-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0022_auto_20180903_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
