# Generated by Django 2.1.1 on 2018-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_site', '0024_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.IntegerField(choices=[(1, 'самовывоз'), (2, 'доставка')], null=True),
        ),
    ]
