# Generated by Django 2.1.1 on 2018-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0026_auto_20180907_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
