# Generated by Django 2.1.1 on 2018-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0027_auto_20180908_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Безналичные', 'Безналичные')], max_length=50,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], max_length=50,
                                   null=True),
        ),
    ]
