# Generated by Django 2.1.1 on 2018-09-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0028_auto_20180908_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_ruble',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
