# Generated by Django 2.1.1 on 2018-09-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0029_orderitem_price_ruble'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='san_site.Currency'),
            preserve_default=False,
        ),
    ]
