# Generated by Django 2.1.1 on 2018-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0030_orderitem_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guid',
            field=models.CharField(db_index=True, default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('ВОбработке', 'В обработке'), ('Выполнен', 'Выполнен'),
                                            ('Отменен', 'Отменен')], default='Новый', max_length=50, null=True),
        ),
    ]
