# Generated by Django 2.1.1 on 2018-09-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0031_auto_20180908_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guid',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('ВОбработке', 'В обработке'), ('Выполнен', 'Выполнен'),
                                            ('Отменен', 'Отменен')], default='Новый', max_length=50),
        ),
    ]
