# Generated by Django 2.1.1 on 2018-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0032_auto_20180908_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
