# Generated by Django 2.1.1 on 2018-09-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0033_auto_20180909_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='san_site.Currency'),
        ),
    ]
