# Generated by Django 2.1.1 on 2018-09-09 17:10

import django.db.models.deletion
from django.db import migrations, models

import san_site.models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0034_auto_20180909_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.ForeignKey(default=san_site.models.Currency.get_ruble, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='san_site.Currency'),
        ),
    ]
