# Generated by Django 2.1.1 on 2018-09-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0035_auto_20180909_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersprices',
            name='value',
        ),
        migrations.AlterField(
            model_name='customersprices',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customersprices',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='product_customers_prices', to='san_site.Product'),
            preserve_default=False,
        ),
    ]
