# Generated by Django 2.1.1 on 2018-09-11 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0036_auto_20180911_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='customersprices',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventories',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='product_inventories', to='san_site.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventories',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='san_site.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT,
                                       to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prices',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='san_site.Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='product_prices', to='san_site.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='san_site.Section'),
            preserve_default=False,
        ),
    ]
