# Generated by Django 2.1.1 on 2018-09-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0037_auto_20180911_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
