# Generated by Django 2.1.1 on 2018-09-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('san_site', '0039_prices_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='stock',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
